### ISSUE TITLE
Not working in Shopware 6.5.5.2 with php 8.2

### ISSUE THREAD

**Issue by VerlooveMaxime** [FriendsOfShopware/FroshPlatformAdminer#20] opened 2023-09-22 11:42 UTC
### PHP Version

8.2

### Shopware Version

6.5.5.2

### Actual behaviour

Upgraded to SW 6.5.5.2 and the FroshPlatformAdminer plugin to 1.0.0. Also upgraded to php 8.2. After upgrading, opening Adminer shows an error message: "Session expired, please login again.". Entering the password does nothing.

What I have tried:
- Clearing cookies
- Changing host to 127.0.0.1 from localhost

### Expected behaviour

Expected to see the contents of the database instead of the login screen. Or at least for the login to work.

### Steps to Reproduce?

Upgraded the store to SW 6.5.5.2 and the FroshPlatformAdminer plugin to 1.0.0.

**Comment by tinect** [comment] 2023-10-23 19:24
Hi @VerlooveMaxime 

I've no problem with that combination.
What type of host you are using?

![image](https://github.com/FriendsOfShopware/FroshPlatformAdminer/assets/135993/cfde1301-a35e-4717-aa58-2f159bcd2065)

**Comment by VerlooveMaxime** [comment] 2023-10-25 09:12
Hello @tinect 

Nothing unsual. Normal stack with Nginx and MySQL. 
Just found out that accessing Adminer.php directly works.

**Comment by tinect** [comment] 2023-10-25 11:24
Hi @VerlooveMaxime 

to be sure: accessing `admin#/frosh/adminer/list` throws a 403? In the iframe? Please share a screenshot.

**Comment by VerlooveMaxime** [comment] 2023-10-26 06:47
@tinect Not really. The admin/adminer route throws the error:
![image](https://github.com/FriendsOfShopware/FroshPlatformAdminer/assets/141220025/cea6284c-4a29-4754-84bc-b0ecec7c8873)
The login route works, so fetching the db credentials from the env variables works.

Yeah, copying Adminer.php to the public folder and accessing it directly works. I can login there with db credentials.

**Comment by tinect** [comment] 2023-11-06 21:10
@VerlooveMaxime do you have any specific Security-Headers set on your hosting?
Could you please verify, if it's happeing after the [require ](https://github.com/FriendsOfShopware/FroshPlatformAdminer/blob/main/src/Controller/AdminerController.php#L55) or before (by shopware) by uncommenting this require?

**Comment by VerlooveMaxime** [comment] 2023-11-07 12:46
@tinect Nothing about the hosting setup has changed since SW 6.4 and the plugin was working fine in that version. 
Commenting the require part loads the page just fine.

**Comment by tinect** [comment] 2024-05-23 20:16
While we cannot reproduce this issue in any way, we need to close this issue here.

Please create a new issue, whenever you could help us to reproduce the issue on any default way.

**Closed by tinect** 2024-05-23 20:16 UTC
Labels: kind/bug

**Comment by petritz** [comment] 2024-07-02 11:37
I have the same issue. @VerlooveMaxime did you solve it from your side?

**Comment by VerlooveMaxime** [comment] 2024-07-02 11:47
Unfortunately not. It's really weird because we have multiple clients that
we upgraded from 6.4 to 6.5 and it only happened to one of them. As a
workaround we copied adminer.php to a publicly accessible folder and logged
in that way. Then we removed the adminer file again once done.

**Comment by petritz** [comment] 2024-07-02 11:50
Thanks for the response. I noticed the same... Especially because a direct clone of the shop on the same server works like a charm. @tinect would you be willing to check the issue directly on the client shop? Thanks

**Comment by tinect** [comment] 2024-07-05 22:10
@petritz feel free to contact me in slack of shopware.
